name: Deploy

on: push


jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Create dir and file
              run: |
                mkdir -p slides/
                echo "Test" > ./slides/file.txt
            # Deploy
            - uses: nekitcorp/yandex-storage-website-action@v1
              with:
                  accessKeyId: ${{ secrets.ID }}
                  secretAccessKey: ${{ secrets.SECRET }}
                  bucket: ${{ secrets.BUCKET }}
                  localPath: "./slides"
                  remotePath: "./slides"
                  clear: true
