# This is a basic workflow to help you get started with Actions

name: Terraform

on:
     push:
            branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout
             uses: actions/checkout@v3
           - name: Setup Terraform
             uses: hashicorp/setup-terraform@v1
           - name: Terraform Init
             id: init
             run: terraform init
           - name: Terraform Plan
             id: plan
             run: terraform plan
             continue-on-error: true
           - name: Terraform Apply
             if:  github.event_name == 'push'
             run: terraform apply -auto-approve -input=false
